import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Fanny",
      email: "client@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Samsung Galaxy A01",
      category: "Smartphones",
      image: "/images/p1.jpg",
      price: 1870,
      countInStock: 20,
      brand: "Samsung",
      rating: 2.5,
      numReviews: 10,
      description: `16GB Internal storage, 1GB RAM, 3000mAh Battery, 
      4G Lite GSM, 5.3" screen, Android 10, 8MP Main camera and 5MP frontal camera.`,
    },
    {
      name: "Xiaomi Redmi Note 9",
      category: "Smartphones",
      image: "/images/p2.jpg",
      price: 4120,
      countInStock: 15,
      brand: "Xiaomi",
      rating: 5,
      numReviews: 17,
      description: `128GB Internal storage, 5020mAh Battery,
      6.53" screen, Android 9.0, 48MP Main camera and 13MP frontal camera.`,
    },
    {
      name: "Huawei P40 Lite",
      category: "Smartphones",
      image: "/images/p3.jpg",
      price: 5478,
      countInStock: 0,
      brand: "Huawei",
      rating: 4.5,
      numReviews: 15,
      description: `128GB Internal storage, 6GB RAM, 4200mAh Battery,
      6.4" screen, Android 10, 48MP Main camera and 16MP frontal camera`,
    },
    {
      name: "Samsung Galaxy Tab A T290",
      category: "Tablets",
      image: "/images/p4.jpg",
      price: 2799,
      countInStock: 8,
      brand: "Samsung",
      rating: 3.5,
      numReviews: 13,
      description: `32GB Internal storage, 2GB RAM, 5100mAh Battery,
      8" screen, Android 8, 8MP Main camera and 2MP frontal camera`,
    },
    {
      name: "Huawei MatePad T8",
      category: "Tablets",
      image: "/images/p5.jpg",
      price: 3760,
      countInStock: 15,
      brand: "Huawei",
      rating: 3.5,
      numReviews: 11,
      description: `16GB Internal storage, 2GB RAM, 5100mAh Battery,
      8" screen, Android 10, 5MP Main camera and 2MP frontal camera`,
    },
    {
      name: "Lenovo Tab M8",
      category: "Tablets",
      image: "/images/p6.jpg",
      price: 2387,
      countInStock: 12,
      brand: "Lenovo",
      rating: 3.5,
      numReviews: 12,
      description: `16GB Internal storage, 2GB RAM, 5000mAh Battery,
      8" screen, Android 9, 5MP Main camera and 2MP frontal camera`,
    },
  ],
};

export default data;
